namespace McpSandbox.Api.Contracts.Availabilities;

public abstract record AvailabilityRequestBase(
    Guid UserId,
    DateOnly EffectiveFrom,
    DateOnly? EffectiveTo,
    bool IsActive,
    DayTimeRangeDto? Sunday,
    DayTimeRangeDto? Monday,
    DayTimeRangeDto? Tuesday,
    DayTimeRangeDto? Wednesday,
    DayTimeRangeDto? Thursday,
    DayTimeRangeDto? Friday,
    DayTimeRangeDto? Saturday,
    IReadOnlyList<Guid>? OfficeIds);

public sealed record CreateAvailabilityRequest(
    Guid UserId,
    DateOnly EffectiveFrom,
    DateOnly? EffectiveTo,
    bool IsActive,
    DayTimeRangeDto? Sunday,
    DayTimeRangeDto? Monday,
    DayTimeRangeDto? Tuesday,
    DayTimeRangeDto? Wednesday,
    DayTimeRangeDto? Thursday,
    DayTimeRangeDto? Friday,
    DayTimeRangeDto? Saturday,
    IReadOnlyList<Guid>? OfficeIds) : AvailabilityRequestBase(
        UserId,
        EffectiveFrom,
        EffectiveTo,
        IsActive,
        Sunday,
        Monday,
        Tuesday,
        Wednesday,
        Thursday,
        Friday,
        Saturday,
        OfficeIds);

public sealed record UpdateAvailabilityRequest(
    Guid UserId,
    DateOnly EffectiveFrom,
    DateOnly? EffectiveTo,
    bool IsActive,
    DayTimeRangeDto? Sunday,
    DayTimeRangeDto? Monday,
    DayTimeRangeDto? Tuesday,
    DayTimeRangeDto? Wednesday,
    DayTimeRangeDto? Thursday,
    DayTimeRangeDto? Friday,
    DayTimeRangeDto? Saturday,
    IReadOnlyList<Guid>? OfficeIds) : AvailabilityRequestBase(
        UserId,
        EffectiveFrom,
        EffectiveTo,
        IsActive,
        Sunday,
        Monday,
        Tuesday,
        Wednesday,
        Thursday,
        Friday,
        Saturday,
        OfficeIds);

public sealed record AvailabilityDto(
    Guid Id,
    Guid UserId,
    DateOnly EffectiveFrom,
    DateOnly? EffectiveTo,
    bool IsActive,
    DayTimeRangeDto? Sunday,
    DayTimeRangeDto? Monday,
    DayTimeRangeDto? Tuesday,
    DayTimeRangeDto? Wednesday,
    DayTimeRangeDto? Thursday,
    DayTimeRangeDto? Friday,
    DayTimeRangeDto? Saturday,
    IReadOnlyList<Guid> OfficeIds,
    DateTimeOffset CreatedAt,
    DateTimeOffset? UpdatedAt);
